[camera]
framerate = 32
width = 1080
height = 720

[haarcascades]
scale_factor = 1.1
min_neighbors = 3
min_size = [30, 30]

[server]
secret = "secret"
endpoint = 'http://my-eden-server.com:6200/data'
batch_size = 1000

[agent]
name = "Raspberry 1" # A device identifier
role = "camera"
