[camera]
framerate = 32
width = 1088
height = 720
mark_faces = false

[haarcascades]
scale_factor = 1.1
min_neighbors = 3
min_size = [30, 30]

[eden-server]
secret = "asdf"
endpoint = 'http://my-eden-server.com:6200/data'
batch_size = 1000

[mjpeg-server]
host = "0.0.0.0"
port = 12345
enable = false

[agent]
name = "Raspberry 1" # A device identifier
role = "camera"
